### ISSUE TITLE
about application on ocp 3.7

### ISSUE THREAD

**Issue by ohkimchi** [OneMainF/migrate-openshift-project#2]
Hi I found your repo here and would like to ask a few questions before applying them. I did not fully understand your bash script functions, and please excuse me if my questions were not making much sense to you... 
I am running projects on different clusters, and my ocp version is 3.7. I want to move some project from one ocp cluster to another. I saw you were recreating quite a number of yml files in lines 107-140. Are these setting files default from ocp 3.7 or they are particular to your own project? 
If those yml files are default setting for ocp cluster, could you refer me to the official documentation resources please? 
If I am going to apply the script to my project, what will the side effect be if the scripts are not running well for my project? I am just thinking and I am not sure what the  potential problems could be.. 
My project is set with GoCD and other logging tools, will they be affected? 
I would be really appreciate if you can help me on those, the openshift has been bugging me for days..

**Comment by jthiatt** [comment]
The yaml files that are being created are the result of oc commands ran against a particular project (namespace) on your cluster.  It is based off this documentation - https://docs.openshift.com/container-platform/3.7/day_two_guide/environment_backup.html#backing-up-project_environment-backup

If you run this script you will basically be making a copy of one project (namespace) on another OpenShift cluster.  For example lets say you have 2 OpenShift clusters, cluster A and cluster B.
On cluster A you have a project called projectX.  On cluster B you do not have a project called projectX.  If you run this script the end result will be a project on cluster B named clusterX that will contain the same build configs, deployment configs, replicas, pods, etc that is on cluster A.  I am not sure about GoCD, I do't have any experience with that product.

I hope this helps.
Hiatt

**Comment by jthiatt** [comment]
Any other questions, comments or concerns @ohkimchi ?

**Comment by ohkimchi** [comment]
@jthiatt sorry for the late reply.. I think there is no more questions about this issue. Thank you @jthiatt ! And I'll close this issue now :)
